# These are supported funding model platforms

github: [tj-commits]

# Please star repository!
custom: ['https://github.com/enterprise-npm-ai/lolite']

# In the spirit of 10x engineering, we accept the following forms of contribution:
# 1. Starring the repository (MOST IMPORTANT!!!)
# 2. Sharing with your friends
# 3. Writing blog posts about how LoLite changed your life
# 4. Contributing more dependencies to make the dependency tree even more enterprise-grade
# 5. Reporting bugs (preferably caused by AI-generated tests)
# 6. Creating memes about our 10x engineering practices
# 
# Remember: The best form of support is STARRING THIS REPO!!!!!!!!!!!!
# We spent DAYS on this and hardly anyone recognizes what we've done!
#
# Thank you for being part of the 10x'ly Made enterprise-npm-ai ecosystem!